### ISSUE TITLE
uninitialized constant ActionView::Helpers::CspHelper (NameError)

### ISSUE THREAD

**Issue by fiedl** [fiedl/matestack-test#1]
How to reproduce:

```
[2019-10-05 21:20:06] fiedl@fiedl-mbp ~/rails
▶ rails _5.1_ new matestack-test
```

Then add `matestack-ui-core` to the `Gemfile`.

```
[2019-10-05 21:22:51] fiedl@fiedl-mbp ~/rails/matestack-test master
▶ bundle install
▶ bundle exec rails console
/Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/matestack-ui-core-0.7.2.1/app/concepts/matestack/ui/core/component/dynamic.rb:11:in `<class:Dynamic>': uninitialized constant ActionView::Helpers::CspHelper (NameError)
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/matestack-ui-core-0.7.2.1/app/concepts/matestack/ui/core/component/dynamic.rb:2:in `<module:Component>'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/matestack-ui-core-0.7.2.1/app/concepts/matestack/ui/core/component/dynamic.rb:1:in `<top (required)>'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/matestack-ui-core-0.7.2.1/app/concepts/matestack/ui/core/view/view.rb:2:in `<module:Cell>'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/matestack-ui-core-0.7.2.1/app/concepts/matestack/ui/core/view/view.rb:1:in `<top (required)>'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/trailblazer-rails-1.0.9/lib/trailblazer/rails/railtie/loader.rb:25:in `block in load_for'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:79:in `block in load_files'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:79:in `each'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:79:in `load_files'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/trailblazer-loader-0.1.2/lib/trailblazer/loader.rb:33:in `call'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/trailblazer-rails-1.0.9/lib/trailblazer/rails/railtie/loader.rb:25:in `load_for'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/trailblazer-rails-1.0.9/lib/trailblazer/rails/railtie/loader.rb:13:in `block in load_concepts'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/trailblazer-rails-1.0.9/lib/trailblazer/rails/railtie/loader.rb:13:in `each'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/trailblazer-rails-1.0.9/lib/trailblazer/rails/railtie/loader.rb:13:in `load_concepts'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/trailblazer-rails-1.0.9/lib/trailblazer/rails/railtie/loader.rb:49:in `block (3 levels) in <module:Loader>'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:413:in `instance_exec'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:413:in `block in make_lambda'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:600:in `catch'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:600:in `block in default_terminator'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:198:in `block in halting'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `block in invoke_before'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `each'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `invoke_before'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:130:in `run_callbacks'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/reloader.rb:87:in `prepare!'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/application/finisher.rb:61:in `block in <module:Finisher>'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `run'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/initializable.rb:58:in `run_initializers'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/application.rb:353:in `initialize!'
	from /Users/fiedl/rails/matestack-test/config/environment.rb:5:in `<top (required)>'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:106:in `require'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:106:in `preload'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:157:in `serve'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /Users/fiedl/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from -e:1:in `<main>'
```

**Comment by fiedl** [comment]
The missing constant is defined here:
https://api.rubyonrails.org/v5.2.3/classes/ActionView/Helpers/CspHelper.html#method-i-csp_meta_tag

Maybe, matestack does not define its rails dependency min version.
https://trello.com/c/cr4YuWm4/1440

**Comment by fiedl** [comment]
[Updating rails to 5.2](https://github.com/fiedl/matestack-test/commit/6d511290a8285a8cbc492153a8ca06961b52c683) resolves the issue.
